- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Including variables for BAstion host
      include_vars: vars/vpc_vars
    - name: Including variables for BAstion host
      include_vars: vars/output_vars

    - name: Creating Key pair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
    - name: Storing provate key locally
      copy:
        content: "{{key_out.key.private_key}}"
        dest: ./vprofile-privkey.pem
        mode: 600
      when: key_out.changed == True

    - name: Creating SG 
      ec2_group:
        name: "BastionHost-SG"
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        description: Creating SG for Bastion host & App stack
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: bastionSG_out

    - name: Storing the BastionHost-SG ID in vprofilestacksetup variable file
      blockinfile:
        path: vars/output_vars
        block: |
          bastion_sg: {{bastionSG_out.group_id}}

    - name: Creating Bastion host instance
      ec2:
          key_name: vprofile-key
          region: "{{region}}"
          image: "{{bastion_ami}}"
          instance_type: t2.micro
          wait: yes
          wait_timeout: 300
          exact_count: 1
          group: "BastionHost-SG"
          vpc_subnet_id: "{{pubsub1id}}"
          instance_tags:
            Name: Bastion host
            Project: Vprofile
          count_tag:
            Name: Bastion host
            Project: Vprofile
      register: bastion_out