- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Including variables for BAstion host
      include_vars: vars/vpc_vars

    - name: Creating Key pair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
    - name: Storing provate key locally
      copy:
        content: "{{key_out.key.private_key}}"
        dest: ./vprofile-privkey.pem
        mode: 600
      when: key_out.changed == True

    - name: Creating SG 
      ec2_group:
        name: "Vprofile-SG"
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: bastion_out