- hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Importing VPC variables
      include_vars: vars/vpc_vars
    
    - name: Creating Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
      register: vpc_out

    - debug:
        var: vpc_out