- hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Importing VPC variables
      include_vars: vars/vpc_vars
    
    - name: Creating Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
      register: vpc_out

    - name: Creating frist public subnet 
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        tags:
          Name: vprofile_pubsub1
      register: pubsub1_out

    - name: Creating 2nd public subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        tags:
          Name: vprofile_pubsub2
      register: pubsub2_out

    - name: Creating 3rd public subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        tags:
          Name: vprofile_pubsub3
      register: pubsub3_out

    - name: Creating 1st Private subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        map_public: yes
        tags:
          Name: vprofile_privsub1
      register: privsub1_out

    - name: Creating 2nd Private subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        map_public: yes
        tags:
          Name: vprofile_privsub2
      register: privsub2_out

    - name: Creating 3rd Private subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        map_public: yes
        tags:
          Name: vprofile_privsub3
      register: privsub3_out

    - name: Creating IGW for public Subnets 
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: vprofile_IGW
      register: vprofile_igw

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile_pubRT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ vprofile_igw.gateway_id }}"
      register: publicRT_out

    - name: Creating a new NAT Gateway 
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{pubsub1_out.subnet.id}}"
        wait: yes
        region: "{{region}}"
        if_exist_do_not_create: true
      register: NATGW_out

    - name: creating private route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile_privRT
        subnets:
          - "{{ privsub1_out.subnet.id }}"
          - "{{ privsub2_out.subnet.id }}"
          - "{{ privsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ NATGW_out.nat_gateway_id }}"
      register: privateRT_out

    - name: Printing all variables & their values
      debug:
        var: "{{item}}"
      loop:
        - vpc_out
        - pubsub1_out
        - pubsub2_out
        - pubsub3_out
        - privsub1_out
        - privsub2_out
        - privsub3_out
        - vprofile_igw
        - publicRT_out
        - NATGW_out
        - privateRT_out

    - name: Storing variables into a file
      copy:
        content: "vpcid: {{vpc_out.vpc.id}}\n
                  pubsub1id: {{pubsub1_out.subnet.id}}\n
                  pubsub2id: {{pubsub2_out.subnet.id}}\n
                  pubsub3id: {{pubsub3_out.subnet.id}}\n
                  privsub1id: {{privsub1_out.subnet.id}}\n
                  privsub2id: {{privsub2_out.subnet.id}}\n
                  privsub3id: {{privsub3_out.subnet.id}}\n
                  igwid: {{vprofile_igw.gateway_id}}\n
                  publicRTid: {{publicRT_out.route_table.id}}\n
                  NATGWid: {{NATGW_out.nat_gateway_id}}\n
                  privateRTid: {{privateRT_out.route_table.id}}\n"
        dest: vars/output_vars