- hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Importing VPC variables
      include_vars: vars/vpc_vars
    
    - name: Creating Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_hostnames: yes
        dns_support: yes
        state: "{{state}}"
      register: vpc_out

    - name: Creating frist public subnet 
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpc_out.vpc.id}}"
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        tags:
          Name: pubsub1
      register: pubsub1_out